### ISSUE TITLE
How set Full Screen automatic?

### ISSUE THREAD

**Issue by onedllpd** [dailymotion/dailymotion-player-sdk-android#11]
I want to know how I can put in automaticly to full screen

**Comment by MrAndrew7of9** [comment]
I don't think this sdk supports this out of the box... you can make a workaround for now. After you define and set your PlayerWebView to a variable in java, you can define your own custom method for making the xml view fullscreen following Android's documentation for doing so. 

In order to not break the default button you'll have to override `.setEventListener()`  on your variable. Then in your switch case block for `PlayerWebView.EVENT_FULLSCREEN_TOGGLE_REQUESTED:` call your own custom method and logic for making the view full screen. Don't forget to toggle the button so the UI doesn't break either. (`myDailyMotionVideoView.setFullScreenButton(isFullScreen)`)
