### ISSUE TITLE
Player don't work on Android 2.3 !

### ISSUE THREAD

**Issue by benju69** [dailymotion/dailymotion-player-sdk-android#3]
Hello,
I have made an application with a videoview, but the video don't play on a Samsung Galaxy S2 and don't play in Genymotion in 2.3; but i's work in fullscreen.
Also the automatic fullscreen option don't work at all.

**Comment by chathura2020** [comment]
any solution for this issue?

**Comment by martinbonnin** [comment]
Hello, the HTML5 player has been updated to work with Android 2.3. Please test and tell us if it is working.

**Comment by chathura2020** [comment]
Hi, Now the player shows the preview image of the video(initially even the preview image hasn't been loaded). But when I click the play button it shows the progress bar and the video is still not playing.

**Comment by martinbonnin** [comment]
My bad, looks like the fix is not completely deployed yet. I will let you know when it is.

**Comment by yuunus90** [comment]
Hi,
This issue is still alive for Android 2.3. Preview image is appearing but when I click the play button it doesn't work. Is there any workaround for this problem or should we find another solutions for Android 2.3? Only thing I can do is directing the 2.3 users to web browser to watch videos instead in app watching.

**Comment by gbaccetta** [comment]
Hi,

This bug is still alive. Are you planning any correction?

**Comment by martinbonnin** [comment]
The player SDK does not support Android 2.3 any more
